import type {
  ClockEventRecord,
  EmployeePayrollProfileRecord,
  EmployeePayrollSensitiveProfileRecord,
  PayPeriodRecord,
  PayrollDocumentRecord,
  PayrollLaborCostAllocationRecord,
  PayrollRunAuditRecord,
  PayrollRunRecord,
  TimeEntryRecord,
  TimesheetAuditRecord,
  TimesheetRecord
} from "../../types/src/index.ts";

export const DEMO_PAY_PERIODS: readonly PayPeriodRecord[] = [
  {
    id: "pay-period-demo-current",
    organizationId: "org-hq",
    status: "open",
    periodStart: "2026-04-27",
    periodEnd: "2026-05-03",
    payDate: "2026-05-08",
    visibilityFlags: ["internal"],
    createdByUserId: "alex.owner",
    closedByUserId: null,
    createdAt: "2026-04-20T12:00:00.000Z",
    updatedAt: "2026-04-27T00:00:00.000Z"
  },
  {
    id: "pay-period-demo-previous",
    organizationId: "org-hq",
    status: "paid",
    periodStart: "2026-04-20",
    periodEnd: "2026-04-26",
    payDate: "2026-05-01",
    visibilityFlags: ["internal"],
    createdByUserId: "alex.owner",
    closedByUserId: "alex.owner",
    createdAt: "2026-04-13T12:00:00.000Z",
    updatedAt: "2026-04-27T18:00:00.000Z"
  }
] as const;

export const DEMO_TIMESHEETS: readonly TimesheetRecord[] = [
  {
    id: "timesheet-demo-admin",
    organizationId: "org-hq",
    employeeUserId: "alex.owner",
    payPeriodId: "pay-period-demo-current",
    status: "open",
    totalMinutes: 90,
    visibilityFlags: ["internal"],
    payrollExportState: "not_ready",
    externalPayrollReference: null,
    submittedByUserId: null,
    approvedByUserId: null,
    submittedAt: null,
    approvedAt: null,
    rejectedAt: null,
    rejectionReason: null,
    lockedAt: null,
    createdAt: "2026-04-27T09:00:00.000Z",
    updatedAt: "2026-04-28T10:00:00.000Z"
  },
  {
    id: "timesheet-demo-employee-1",
    organizationId: "org-hq",
    employeeUserId: "employee-1",
    payPeriodId: "pay-period-demo-current",
    status: "submitted",
    totalMinutes: 450,
    visibilityFlags: ["internal"],
    payrollExportState: "not_ready",
    externalPayrollReference: null,
    submittedByUserId: "employee-1",
    approvedByUserId: null,
    submittedAt: "2026-04-28T12:00:00.000Z",
    approvedAt: null,
    rejectedAt: null,
    rejectionReason: null,
    lockedAt: null,
    createdAt: "2026-04-27T08:00:00.000Z",
    updatedAt: "2026-04-28T12:00:00.000Z"
  },
  {
    id: "timesheet-demo-employee-2",
    organizationId: "org-hq",
    employeeUserId: "employee-2",
    payPeriodId: "pay-period-demo-current",
    status: "open",
    totalMinutes: 240,
    visibilityFlags: ["internal"],
    payrollExportState: "not_ready",
    externalPayrollReference: null,
    submittedByUserId: null,
    approvedByUserId: null,
    submittedAt: null,
    approvedAt: null,
    rejectedAt: null,
    rejectionReason: null,
    lockedAt: null,
    createdAt: "2026-04-27T08:30:00.000Z",
    updatedAt: "2026-04-28T13:30:00.000Z"
  },
  {
    id: "timesheet-demo-employee-2-previous",
    organizationId: "org-hq",
    employeeUserId: "employee-2",
    payPeriodId: "pay-period-demo-previous",
    status: "locked",
    totalMinutes: 300,
    visibilityFlags: ["internal"],
    payrollExportState: "exported",
    externalPayrollReference: "payrun_hist_1",
    submittedByUserId: "employee-2",
    approvedByUserId: "alex.owner",
    submittedAt: "2026-04-26T15:00:00.000Z",
    approvedAt: "2026-04-26T17:00:00.000Z",
    rejectedAt: null,
    rejectionReason: null,
    lockedAt: "2026-04-27T18:00:00.000Z",
    createdAt: "2026-04-20T08:30:00.000Z",
    updatedAt: "2026-04-27T18:00:00.000Z"
  }
] as const;

export const DEMO_CLOCK_EVENTS: readonly ClockEventRecord[] = [
  {
    id: "clock-event-demo-admin-1",
    organizationId: "org-hq",
    employeeUserId: "alex.owner",
    projectId: "project-demo-2",
    taskId: "task-demo-2",
    eventType: "clock_in",
    eventSource: "web",
    occurredAt: "2026-04-28T08:30:00.000Z",
    notes: "Estimate review block",
    recordedByUserId: "alex.owner",
    visibilityFlags: ["internal"],
    createdAt: "2026-04-28T08:30:00.000Z"
  },
  {
    id: "clock-event-demo-admin-2",
    organizationId: "org-hq",
    employeeUserId: "alex.owner",
    projectId: "project-demo-2",
    taskId: "task-demo-2",
    eventType: "clock_out",
    eventSource: "web",
    occurredAt: "2026-04-28T10:00:00.000Z",
    notes: "Estimate review block",
    recordedByUserId: "alex.owner",
    visibilityFlags: ["internal"],
    createdAt: "2026-04-28T10:00:00.000Z"
  },
  {
    id: "clock-event-demo-1",
    organizationId: "org-hq",
    employeeUserId: "employee-1",
    projectId: "project-demo-1",
    taskId: "task-demo-1",
    eventType: "clock_in",
    eventSource: "mobile",
    occurredAt: "2026-04-28T08:00:00.000Z",
    notes: "Electrical rough-in start",
    recordedByUserId: "employee-1",
    visibilityFlags: ["internal"],
    createdAt: "2026-04-28T08:00:00.000Z"
  },
  {
    id: "clock-event-demo-2",
    organizationId: "org-hq",
    employeeUserId: "employee-1",
    projectId: "project-demo-1",
    taskId: "task-demo-1",
    eventType: "break_start",
    eventSource: "mobile",
    occurredAt: "2026-04-28T10:00:00.000Z",
    notes: "Material pickup",
    recordedByUserId: "employee-1",
    visibilityFlags: ["internal"],
    createdAt: "2026-04-28T10:00:00.000Z"
  },
  {
    id: "clock-event-demo-3",
    organizationId: "org-hq",
    employeeUserId: "employee-1",
    projectId: "project-demo-1",
    taskId: "task-demo-1",
    eventType: "break_end",
    eventSource: "mobile",
    occurredAt: "2026-04-28T10:15:00.000Z",
    notes: "Material pickup complete",
    recordedByUserId: "employee-1",
    visibilityFlags: ["internal"],
    createdAt: "2026-04-28T10:15:00.000Z"
  },
  {
    id: "clock-event-demo-4",
    organizationId: "org-hq",
    employeeUserId: "employee-1",
    projectId: "project-demo-1",
    taskId: "task-demo-1",
    eventType: "clock_out",
    eventSource: "mobile",
    occurredAt: "2026-04-28T12:15:00.000Z",
    notes: "Morning rough-in complete",
    recordedByUserId: "employee-1",
    visibilityFlags: ["internal"],
    createdAt: "2026-04-28T12:15:00.000Z"
  },
  {
    id: "clock-event-demo-5",
    organizationId: "org-hq",
    employeeUserId: "employee-1",
    projectId: "project-demo-1",
    taskId: "task-demo-1",
    eventType: "clock_in",
    eventSource: "mobile",
    occurredAt: "2026-04-28T13:00:00.000Z",
    notes: "Afternoon wiring pass",
    recordedByUserId: "employee-1",
    visibilityFlags: ["internal"],
    createdAt: "2026-04-28T13:00:00.000Z"
  },
  {
    id: "clock-event-demo-6",
    organizationId: "org-hq",
    employeeUserId: "employee-1",
    projectId: "project-demo-1",
    taskId: "task-demo-1",
    eventType: "clock_out",
    eventSource: "mobile",
    occurredAt: "2026-04-28T16:30:00.000Z",
    notes: "Afternoon wiring pass",
    recordedByUserId: "employee-1",
    visibilityFlags: ["internal"],
    createdAt: "2026-04-28T16:30:00.000Z"
  },
  {
    id: "clock-event-demo-7",
    organizationId: "org-hq",
    employeeUserId: "employee-2",
    projectId: "project-demo-2",
    eventType: "clock_in",
    eventSource: "mobile",
    occurredAt: "2026-04-28T13:30:00.000Z",
    notes: "Internal planning block",
    recordedByUserId: "employee-2",
    visibilityFlags: ["internal"],
    createdAt: "2026-04-28T13:30:00.000Z"
  }
] as const;

export const DEMO_TIME_ENTRIES: readonly TimeEntryRecord[] = [
  {
    id: "time-entry-demo-admin",
    organizationId: "org-hq",
    employeeUserId: "alex.owner",
    payPeriodId: "pay-period-demo-current",
    timesheetId: "timesheet-demo-admin",
    projectId: "project-demo-2",
    taskId: "task-demo-2",
    clockInEventId: "clock-event-demo-admin-1",
    clockOutEventId: "clock-event-demo-admin-2",
    status: "draft",
    workDate: "2026-04-28",
    startedAt: "2026-04-28T08:30:00.000Z",
    endedAt: "2026-04-28T10:00:00.000Z",
    breakMinutes: 0,
    minutesWorked: 90,
    notes: "Estimate review block",
    visibilityFlags: ["internal"],
    payrollExportState: "not_ready",
    externalPayrollReference: null,
    submittedByUserId: null,
    approvedByUserId: null,
    submittedAt: null,
    approvedAt: null,
    rejectedAt: null,
    rejectionReason: null,
    createdAt: "2026-04-28T10:00:00.000Z",
    updatedAt: "2026-04-28T10:00:00.000Z"
  },
  {
    id: "time-entry-demo-1",
    organizationId: "org-hq",
    employeeUserId: "employee-1",
    payPeriodId: "pay-period-demo-current",
    timesheetId: "timesheet-demo-employee-1",
    projectId: "project-demo-1",
    taskId: "task-demo-1",
    clockInEventId: "clock-event-demo-1",
    clockOutEventId: "clock-event-demo-4",
    status: "submitted",
    workDate: "2026-04-28",
    startedAt: "2026-04-28T08:00:00.000Z",
    endedAt: "2026-04-28T12:15:00.000Z",
    breakMinutes: 15,
    minutesWorked: 240,
    notes: "Morning rough-in complete",
    visibilityFlags: ["internal"],
    payrollExportState: "not_ready",
    externalPayrollReference: null,
    submittedByUserId: "employee-1",
    approvedByUserId: null,
    submittedAt: "2026-04-28T12:00:00.000Z",
    approvedAt: null,
    rejectedAt: null,
    rejectionReason: null,
    createdAt: "2026-04-28T12:15:00.000Z",
    updatedAt: "2026-04-28T12:15:00.000Z"
  },
  {
    id: "time-entry-demo-2",
    organizationId: "org-hq",
    employeeUserId: "employee-1",
    payPeriodId: "pay-period-demo-current",
    timesheetId: "timesheet-demo-employee-1",
    projectId: "project-demo-1",
    taskId: "task-demo-1",
    clockInEventId: "clock-event-demo-5",
    clockOutEventId: "clock-event-demo-6",
    status: "submitted",
    workDate: "2026-04-28",
    startedAt: "2026-04-28T13:00:00.000Z",
    endedAt: "2026-04-28T16:30:00.000Z",
    breakMinutes: 0,
    minutesWorked: 210,
    notes: "Afternoon wiring pass",
    visibilityFlags: ["internal"],
    payrollExportState: "not_ready",
    externalPayrollReference: null,
    submittedByUserId: "employee-1",
    approvedByUserId: null,
    submittedAt: "2026-04-28T12:00:00.000Z",
    approvedAt: null,
    rejectedAt: null,
    rejectionReason: null,
    createdAt: "2026-04-28T16:30:00.000Z",
    updatedAt: "2026-04-28T16:30:00.000Z"
  },
  {
    id: "time-entry-demo-3",
    organizationId: "org-hq",
    employeeUserId: "employee-2",
    payPeriodId: "pay-period-demo-current",
    timesheetId: "timesheet-demo-employee-2",
    projectId: "project-demo-2",
    clockInEventId: null,
    clockOutEventId: null,
    status: "draft",
    workDate: "2026-04-27",
    startedAt: "2026-04-27T09:00:00.000Z",
    endedAt: "2026-04-27T13:00:00.000Z",
    breakMinutes: 0,
    minutesWorked: 240,
    notes: "Initial planning review",
    visibilityFlags: ["internal"],
    payrollExportState: "not_ready",
    externalPayrollReference: null,
    submittedByUserId: null,
    approvedByUserId: null,
    submittedAt: null,
    approvedAt: null,
    rejectedAt: null,
    rejectionReason: null,
    createdAt: "2026-04-27T13:00:00.000Z",
    updatedAt: "2026-04-27T13:00:00.000Z"
  },
  {
    id: "time-entry-demo-4",
    organizationId: "org-hq",
    employeeUserId: "employee-2",
    payPeriodId: "pay-period-demo-previous",
    timesheetId: "timesheet-demo-employee-2-previous",
    projectId: "project-demo-2",
    taskId: "task-demo-2",
    clockInEventId: null,
    clockOutEventId: null,
    status: "approved",
    workDate: "2026-04-24",
    startedAt: "2026-04-24T08:00:00.000Z",
    endedAt: "2026-04-24T13:00:00.000Z",
    breakMinutes: 0,
    minutesWorked: 300,
    notes: "Historical planning allocation",
    visibilityFlags: ["internal"],
    payrollExportState: "exported",
    externalPayrollReference: "payrun_hist_1:line_1",
    submittedByUserId: "employee-2",
    approvedByUserId: "alex.owner",
    submittedAt: "2026-04-26T15:00:00.000Z",
    approvedAt: "2026-04-26T17:00:00.000Z",
    rejectedAt: null,
    rejectionReason: null,
    createdAt: "2026-04-24T13:00:00.000Z",
    updatedAt: "2026-04-27T18:00:00.000Z"
  }
] as const;

export const DEMO_TIMESHEET_AUDIT_RECORDS: readonly TimesheetAuditRecord[] = [
  {
    id: "timesheet-audit-demo-1",
    timesheetId: "timesheet-demo-employee-1",
    action: "submitted",
    actorUserId: "employee-1",
    occurredAt: "2026-04-28T12:00:00.000Z",
    snapshot: {
      status: "submitted",
      totalMinutes: 450,
      payrollExportState: "not_ready",
      rejectionReason: null,
      timeEntryIds: ["time-entry-demo-1", "time-entry-demo-2"]
    }
  }
] as const;

export const DEMO_EMPLOYEE_PAYROLL_PROFILES: readonly EmployeePayrollProfileRecord[] = [
  {
    id: "payroll-profile-admin",
    organizationId: "org-hq",
    employeeUserId: "alex.owner",
    providerName: "embedded_payroll",
    providerEmployeeId: "worker_admin",
    workEmail: "alex.owner@example.com",
    legalName: "Alex Owner",
    status: "active",
    compensationType: "hourly",
    paySchedule: "weekly",
    overtimeEligible: true,
    visibilityFlags: ["internal"],
    createdByUserId: "alex.owner",
    updatedByUserId: "alex.owner",
    onboardedAt: "2026-04-15T12:00:00.000Z",
    offboardedAt: null,
    createdAt: "2026-04-15T12:00:00.000Z",
    updatedAt: "2026-04-28T09:00:00.000Z"
  },
  {
    id: "payroll-profile-employee-1",
    organizationId: "org-hq",
    employeeUserId: "employee-1",
    providerName: "embedded_payroll",
    providerEmployeeId: "worker_employee_1",
    workEmail: "employee-1@example.com",
    legalName: "Sam Carter",
    status: "active",
    compensationType: "hourly",
    paySchedule: "weekly",
    overtimeEligible: true,
    visibilityFlags: ["internal"],
    createdByUserId: "alex.owner",
    updatedByUserId: "alex.owner",
    onboardedAt: "2026-04-15T12:05:00.000Z",
    offboardedAt: null,
    createdAt: "2026-04-15T12:05:00.000Z",
    updatedAt: "2026-04-28T09:00:00.000Z"
  },
  {
    id: "payroll-profile-employee-2",
    organizationId: "org-hq",
    employeeUserId: "employee-2",
    providerName: "embedded_payroll",
    providerEmployeeId: "worker_employee_2",
    workEmail: "employee-2@example.com",
    legalName: "Riley Stone",
    status: "active",
    compensationType: "hourly",
    paySchedule: "weekly",
    overtimeEligible: false,
    visibilityFlags: ["internal"],
    createdByUserId: "alex.owner",
    updatedByUserId: "alex.owner",
    onboardedAt: "2026-04-15T12:10:00.000Z",
    offboardedAt: null,
    createdAt: "2026-04-15T12:10:00.000Z",
    updatedAt: "2026-04-28T09:00:00.000Z"
  }
] as const;

export const DEMO_EMPLOYEE_PAYROLL_SENSITIVE_PROFILES: readonly EmployeePayrollSensitiveProfileRecord[] = [
  {
    id: "payroll-sensitive-admin",
    profileId: "payroll-profile-admin",
    providerWorkerToken: "wrk_tok_worker_admin",
    providerOnboardingUrl: "https://embedded-payroll.local/onboarding/worker_admin",
    maskedTaxId: "***-**-4401",
    bankAccountLast4: "3301",
    laborCostRateCents: 6200,
    updatedByUserId: "alex.owner",
    updatedAt: "2026-04-28T09:00:00.000Z"
  },
  {
    id: "payroll-sensitive-employee-1",
    profileId: "payroll-profile-employee-1",
    providerWorkerToken: "wrk_tok_worker_employee_1",
    providerOnboardingUrl: "https://embedded-payroll.local/onboarding/worker_employee_1",
    maskedTaxId: "***-**-4402",
    bankAccountLast4: "3302",
    laborCostRateCents: 3400,
    updatedByUserId: "alex.owner",
    updatedAt: "2026-04-28T09:00:00.000Z"
  },
  {
    id: "payroll-sensitive-employee-2",
    profileId: "payroll-profile-employee-2",
    providerWorkerToken: "wrk_tok_worker_employee_2",
    providerOnboardingUrl: "https://embedded-payroll.local/onboarding/worker_employee_2",
    maskedTaxId: "***-**-4403",
    bankAccountLast4: "3303",
    laborCostRateCents: 3000,
    updatedByUserId: "alex.owner",
    updatedAt: "2026-04-28T09:00:00.000Z"
  }
] as const;

export const DEMO_PAYROLL_RUNS: readonly PayrollRunRecord[] = [
  {
    id: "payroll-run-demo-history-1",
    organizationId: "org-hq",
    payPeriodId: "pay-period-demo-previous",
    providerName: "embedded_payroll",
    providerRunId: "payrun_hist_1",
    status: "completed",
    approvedTimesheetCount: 1,
    approvedTimeEntryCount: 1,
    totalMinutes: 300,
    totalLaborCostCents: 15000,
    failureReason: null,
    visibilityFlags: ["internal"],
    createdByUserId: "alex.owner",
    submittedAt: "2026-04-27T17:30:00.000Z",
    syncedAt: "2026-04-27T18:00:00.000Z",
    completedAt: "2026-04-27T18:00:00.000Z",
    failedAt: null,
    createdAt: "2026-04-27T17:30:00.000Z",
    updatedAt: "2026-04-27T18:00:00.000Z"
  }
] as const;

export const DEMO_PAYROLL_RUN_AUDITS: readonly PayrollRunAuditRecord[] = [
  {
    id: "payroll-run-audit-demo-1",
    payrollRunId: "payroll-run-demo-history-1",
    action: "export_started",
    actorUserId: "alex.owner",
    fromStatus: "draft",
    toStatus: "submitted",
    occurredAt: "2026-04-27T17:30:00.000Z"
  },
  {
    id: "payroll-run-audit-demo-2",
    payrollRunId: "payroll-run-demo-history-1",
    action: "completed",
    actorUserId: "alex.owner",
    fromStatus: "submitted",
    toStatus: "completed",
    occurredAt: "2026-04-27T18:00:00.000Z"
  }
] as const;

export const DEMO_PAYROLL_DOCUMENTS: readonly PayrollDocumentRecord[] = [
  {
    id: "payroll-document-demo-1",
    organizationId: "org-hq",
    employeeUserId: "employee-2",
    payrollRunId: "payroll-run-demo-history-1",
    providerName: "embedded_payroll",
    category: "paystub",
    title: "Weekly paystub",
    fileName: "employee-2-paystub-2026-04-26.pdf",
    externalDocumentId: "doc_payrun_hist_1_employee_2",
    downloadUrl: "https://embedded-payroll.local/documents/payrun_hist_1/employee-2",
    issuedAt: "2026-04-27T18:00:00.000Z",
    visibilityFlags: ["internal"],
    createdAt: "2026-04-27T18:00:00.000Z"
  }
] as const;

export const DEMO_PAYROLL_LABOR_COST_ALLOCATIONS: readonly PayrollLaborCostAllocationRecord[] = [
  {
    id: "payroll-cost-demo-1",
    organizationId: "org-hq",
    payrollRunId: "payroll-run-demo-history-1",
    payPeriodId: "pay-period-demo-previous",
    employeeUserId: "employee-2",
    timeEntryId: "time-entry-demo-4",
    projectId: "project-demo-2",
    taskId: "task-demo-2",
    minutesWorked: 300,
    laborCostCents: 15000,
    createdAt: "2026-04-27T18:00:00.000Z"
  }
] as const;
